## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details
language: java
jdk:
  - oraclejdk8

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - chmod +x bin/*

# command to run tests
script: cd src/ontology && make test

# whitelist
branches:
  only:
    - master
    - test-travis

### UNCOMMENT THIS AND ADD YOUR DETAILS:
notifications:
  email:
    - jupp@ebi.ac.uk                                                                                                   |
#    - emily@ebi.ac.uk                                                                                              |
